name: Deploy to KinD Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up KinD cluster
      - name: Set up KinD cluster
        uses: helm/kind-action@v1.4.0
        with:
          version: v0.20.0

      # Step 3: Configure kubectl
      - name: Configure kubectl
        run: |
          kubectl cluster-info
          kubectl get nodes

      # Step 4: Apply Kubernetes manifests
      - name: Deploy application
        run: |
          kubectl apply -f .

      - name: Wait for pod readiness
        run: |
          kubectl wait --for=condition=ready pod -l app=guestbook-ui --timeout=30s


      # Step 5: Port forward the service
      - name: Forward port to access application
        run: |
          nohup kubectl port-forward service/guestbook-ui 8080:8010 &
          sleep 5

      # Step 6: Test application access
      - name: Test application
        run: |
          curl http://localhost:8080


   
